IKProject/IKProject_2512/IKProject_2512/IKProject_2512/Areas/Platform/Controllers/MembershipController.cs
using IKProject_2512.Areas.Platform.Models;
using IKProject_2512.Database;
using IKProject_2512.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace IKProject_2512.Areas.Platform.Controllers
{
    [Area("Platform")]
    public class MembershipController : Controller
    {
        private readonly IKDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public MembershipController(IKDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult MembershipList()
        {
            var mShipList = _context.MembershipPackages.Where(x=>x.IsActive==true).ToList();
            return View(mShipList);
        }


        [HttpGet]
        public IActionResult CreatePackage()
        {
            PackageModel mShipPack = new PackageModel();
            return View(mShipPack);
        }

        [HttpPost]
        public IActionResult CreatePackage(PackageModel membership)
        {
            if (ModelState.IsValid)
            {
                if (membership.PhotoFile != null)
                {
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(membership.PhotoFile.FileName);
                    string extension = Path.GetExtension(membership.PhotoFile.FileName);

                    membership.PhotoPath = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    string path = Path.Combine(wwwRootPath + "/ImageFile", fileName);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        membership.PhotoFile.CopyTo(fileStream);
                    }
                }
                MembershipPackage newPackage = new MembershipPackage();
                newPackage.PhotoPath = membership.PhotoPath;
                newPackage.PackageName = membership.PackageName;
                newPackage.PackageMaxCapacity= membership.PackageMaxCapacity;
                newPackage.PackageBasePrice= membership.PackageBasePrice;
                newPackage.IsActive = true;

                _context.MembershipPackages.Add(newPackage);
                _context.SaveChanges();
                return RedirectToAction(nameof(MembershipList));
            }
            return View(membership);
        }
        [HttpGet]
        public IActionResult MShipEdit(int id)
        {
            var package = _context.MembershipPackages.Find(id);
            PackageModel sentPackage = new PackageModel();
            sentPackage.PackageName = package.PackageName;
            sentPackage.PackageMaxCapacity = package.PackageMaxCapacity;
            sentPackage.PackageBasePrice = package.PackageBasePrice;
            sentPackage.PhotoPath = package.PhotoPath;
            sentPackage.PackageID = package.PackageID;

            return View(sentPackage);
        }
        [HttpPost]
        public IActionResult MShipEdit(PackageModel package)
        {
            if (ModelState.IsValid)
            {
                var newPackage = _context.MembershipPackages.Find(package.PackageID);
                newPackage.PackageName = package.PackageName;
                newPackage.PackageMaxCapacity = package.PackageMaxCapacity;
                newPackage.PackageBasePrice = package.PackageBasePrice;
                newPackage.IsActive = true;
                _context.MembershipPackages.Update(newPackage);
                _context.SaveChanges();
                return RedirectToAction(nameof(MembershipList));
            }
            return View(package);
        }
        [HttpGet]
        public IActionResult MShipDetails(int id)
        {
            var package = _context.MembershipPackages.Find(id);
            return View(package);
        }

        [HttpGet]
        public IActionResult MShipDefinedCoList(int id)
        {
            var package = _context.MembershipPackages.Find(id).PackageID;
            var cp = _context.CompanyPackages.Where(x => x.PackageID == package).ToList();
            ViewBag.PackageID = id;
            ViewBag.PackageName = _context.MembershipPackages.Find(id).PackageName;
            return View(cp);
        }
        [HttpPost]
        public IActionResult MShipDefinedCoList(int id, string name)
        {
            var package = _context.MembershipPackages.Find(id);
            package.IsActive = false;
            _context.Update(package);
            _context.SaveChanges();
            return RedirectToAction(nameof(MembershipList));
        }

        [HttpGet]
        public IActionResult PassiveMembershipList()
        {
            var passivePackages = _context.MembershipPackages.Where(x => x.IsActive == false).ToList();
            return View(passivePackages);
        }
    }
}

IKProject/IKProject_2512/IKProject_2512/IKProject_2512/Areas/Platform/Views/Membership/CreatePackage.cshtml
@model IKProject_2512.Areas.Platform.Models.PackageModel

@{
    ViewData["Title"] = "CreatePackage";
}
<style>
    .form {
        background: rgba(255,255,255,0.9);
        padding: 40px;
        max-width: 600px;
        margin: 40px auto;
        border-radius: 10px;
        box-shadow: 0 0 20px 2px rgba(0,0,0,0.5);
    }

    h2 {
        text-align: center;
        text-shadow: 0 0 20px 2px rgba(0,0,0,0.9);
        color: deepskyblue;
        font-weight: 800;
        margin: 0 0 30px;
    }
    .form-input {
        width: 300px;
        padding: 20px;
        background: #fff;
        border: 2px dashed #555;
    }

        .form-input input {
            display: none;
        }

        .form-input label {
            display: block;
            width: 100px;
            height: 50px;
            line-height: 50px;
            text-align: center;
            background: #333;
            color: #fff;
            font-size: 12px;
            font-weight: 500;
            border-radius: 10px;
            cursor: pointer;
        }

        .form-input img {
            width: 100px;
            display: none;
            margin-top: 5px;
        }
</style>
<div class="form">
    <h2>Yeni Üyelik Paketi Oluştur</h2>
    <form asp-action="CreatePackage" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        @*<div class="form-group" style="border:2px solid gray;border-radius:2px;">
            <label asp-for="PhotoFile" class="control-label"></label>
            <input type="file" asp-for="PhotoFile" class="form-control-file" />
        </div>*@
        <div class="form-input">
            <label for="file-ip-1">FotoğrafYükle</label>
            <input type="file" asp-for="PhotoFile" id="file-ip-1" accept="image/*" onchange="showPreview(event);" />
            <div class="preview m-1">
                <img id="file-ip-1-preview" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="PackageName" class="control-label"></label>
            <input asp-for="PackageName" class="form-control" />
            <span asp-validation-for="PackageName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PackageMaxCapacity" class="control-label"></label>
            <input asp-for="PackageMaxCapacity" class="form-control" />
            <span asp-validation-for="PackageMaxCapacity" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PackageBasePrice" class="control-label"></label>
            <input asp-for="PackageBasePrice" class="form-control" />
            <span asp-validation-for="PackageBasePrice" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Kaydet" class="btn btn-info" />
            <a class="btn btn-danger" asp-area="Platform" asp-controller="Membership" asp-action="MembershipList">Üyelik Paketleri Listesine Git</a>
        </div>
    </form>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    function showPreview(event) {
        if (event.target.files.length > 0) {
            var src = URL.createObjectURL(event.target.files[0]);
            var preview = document.getElementById("file-ip-1-preview");
            preview.src = src;
            preview.style.display = "block";

        }
    }
</script>

IKProject/IKProject_2512/IKProject_2512/IKProject_2512/Areas/Platform/Views/Membership/MShipDefinedCoList.cshtml
@model IEnumerable<IKProject_2512.Models.CompanyPackage>

@{
    ViewData["Title"] = "MShipDefinedCoList";
}

<h1>Silmek İstenen Pakete Tanımlı Şirketler Listesi</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Company.Logo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Company.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Package)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MembershipMonthlyPeriod)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MembershipPackagePrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PackageStartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PackageRemainingMonths)
                <span>(Aylık)</span>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="@("~/ImageFile/"+item.Company.Logo)" asp-append-version="true" width="200" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Company.CompanyName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Package.PackageName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MembershipMonthlyPeriod)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MembershipPackagePrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PackageStartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PackageRemainingMonths)
                </td>
                <td>
                </td>
            </tr>
        }
    </tbody>
</table>
<form asp-action="MshipDefinedCoList" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <input type="submit" value="Paketi Sil" asp-route-id="@ViewBag.PackageID" asp-route-name="@ViewBag.PackageName" class="btn btn-danger" /> |
    <a class="btn btn-info" asp-area="Platform" asp-controller="Membership" asp-action="MembershipList">Listeye Geri Dön</a>
</form>

IKProject/IKProject_2512/IKProject_2512/IKProject_2512/Areas/Platform/Views/Membership/MShipDetails.cshtml
@model IKProject_2512.Models.MembershipPackage

@{
    ViewData["Title"] = "MShipDetails";
}
<style>
    .form {
        background: rgba(255,255,255,0.9);
        padding: 40px;
        max-width: 600px;
        margin: 40px auto;
        border-radius: 10px;
        box-shadow: 0 0 20px 2px rgba(0,0,0,0.5);
    }

    h2 {
        text-align: center;
        text-shadow: 0 0 20px 2px rgba(0,0,0,0.9);
        color: deepskyblue;
        font-weight: 800;
        margin: 0 0 30px;
    }

    dt, dd {
        color: black;
        text-align: left;
    }
</style>

<div class="form">
    <h2>Üyelik Paket Detayları</h2>

    <dl class="row">
        <dd class="col-sm-12">
            <img src="@("~/ImageFile/"+Model.PhotoPath)" asp-append-version="true" width="80" />
        </dd>

        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.PackageName)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.PackageName)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.PackageMaxCapacity)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.PackageMaxCapacity)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.PackageBasePrice)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.PackageBasePrice)
        </dd>

    </dl>
    <div>
        <a class="btn btn-info" asp-area="Platform" asp-controller="Membership" asp-action="MShipEdit" asp-route-id="@Model.PackageID">Düzenle</a> |
        <a class="btn btn-danger" asp-area="Platform" asp-controller="Membership" asp-action="MembershipList">Listeye Geri Dön</a>
    </div>
</div>

IKProject/IKProject_2512/IKProject_2512/IKProject_2512/Areas/Platform/Views/Membership/MShipEdit.cshtml
@model IKProject_2512.Areas.Platform.Models.PackageModel

@{
    ViewData["Title"] = "MShipEdit";
}
<style>
    .form {
        background: rgba(255,255,255,0.9);
        padding: 40px;
        max-width: 600px;
        margin: 40px auto;
        border-radius: 10px;
        box-shadow: 0 0 20px 2px rgba(0,0,0,0.5);
    }
    h2 {
        text-align: center;
        text-shadow: 0 0 20px 2px rgba(0,0,0,0.9);
        color: deepskyblue;
        font-weight: 800;
        margin: 0 0 30px;
    }
</style>
<div class="form">
    <h2>Üyelik Paketi Düzenleme</h2>
    <img src="@("~/ImageFile/"+Model.PhotoPath)" asp-append-version="true" width="100" />
    <form asp-action="MShipEdit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="PackageID" />
        <input type="hidden" asp-for="PhotoPath" />
        <div class="form-group">
            <label asp-for="PackageName" class="control-label"></label>
            <input asp-for="PackageName" class="form-control" />
            <span asp-validation-for="PackageName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PackageMaxCapacity" class="control-label"></label>
            <input asp-for="PackageMaxCapacity" class="form-control" />
            <span asp-validation-for="PackageMaxCapacity" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PackageBasePrice" class="control-label"></label>
            <input asp-for="PackageBasePrice" class="form-control" />
            <span asp-validation-for="PackageBasePrice" class="text-danger"></span>
        </div>

        <div class="form-group">

            <input type="submit" value="Kaydet" class="btn btn-primary" /> | 
            <a class="btn btn-danger" asp-area="Platform" asp-controller="Membership" asp-action="MembershipList">Üyelik Paketleri Listesine Geri Dön</a>
        </div>
    </form>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IKProject/IKProject_2512/IKProject_2512/IKProject_2512/Areas/Platform/Views/Membership/MembershipList.cshtml
@model IEnumerable<IKProject_2512.Models.MembershipPackage>

@{
    ViewData["Title"] = "MembershipList";
}

<h4>Üyelik Paketleri</h4>

<p>
    <a class="btn btn-info" asp-area="Platform" asp-controller="Membership" asp-action="PassiveMembershipList">Pasif Paketleri Görüntüle</a>  | 
    <a class="btn btn-danger" asp-area="Platform" asp-controller="Membership" asp-action="CreatePackage">Yeni Üyelik Paketi Yarat</a>
</p>
<table class="table table-primary table-hover table-active table-info">
    <thead>
        <tr>
            <th>
                Paket Logosu
            </th>
            <th>
                Paket Adı
            </th>
            <th>
                Paket Kapasitesi
            </th>
            <th>
                Aylık Paket Fiyatı
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <img src="@("~/ImageFile/"+item.PhotoPath)" asp-append-version="true" width="200" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PackageName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PackageMaxCapacity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PackageBasePrice)
            </td>

            <td>
                <a class="btn btn-dark" asp-area="Platform" asp-controller="Membership" asp-action="MShipEdit" asp-route-id="@item.PackageID">Düzenle</a> |
                <a class="btn btn-primary" asp-area="Platform" asp-controller="Membership" asp-action="MShipDetails" asp-route-id="@item.PackageID">Detaylar</a>|
                <a class="btn btn-danger" asp-area="Platform" asp-controller="Membership" asp-action="MShipDefinedCoList" asp-route-id="@item.PackageID">Paketi Sil</a>

            </td>
        </tr>
}
    </tbody>
</table>

@*<div class="header_fixed">
    <table>
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PhotoPath)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PackageName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PackageMaxCapacity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PackageBasePrice)
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <img src="@("~/ImageFile/"+item.PhotoPath)" asp-append-version="true" width="200" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PackageName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PackageMaxCapacity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PackageBasePrice)
                    </td>

                    <td>
                        <a class="btn btn-dark" asp-area="Platform" asp-controller="Membership" asp-action="MShipEdit" asp-route-id="@item.PackageID">Düzenle</a> |
                        <a class="btn btn-primary" asp-area="Platform" asp-controller="Membership" asp-action="MShipDetails" asp-route-id="@item.PackageID">Detaylar</a>|
                        <a class="btn btn-danger" asp-area="Platform" asp-controller="Membership" asp-action="MShipDefinedCoList" asp-route-id="@item.PackageID">Paketi Sil</a>

                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>*@

IKProject/IKProject_2512/IKProject_2512/IKProject_2512/Areas/Platform/Views/Membership/PassiveMembershipList.cshtml
@model IEnumerable<IKProject_2512.Models.MembershipPackage>

@{
    ViewData["Title"] = "MembershipList";
}

<h1>Pasif Üyelik Paketleri Listesi</h1>

<table class="table table-primary table-hover table-active table-info">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PhotoPath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PackageName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PackageMaxCapacity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PackageBasePrice)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="@("~/ImageFile/"+item.PhotoPath)" asp-append-version="true" width="200" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PackageName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PackageMaxCapacity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PackageBasePrice)
                </td>
            </tr>
        }
    </tbody>
</table>
<a asp-area="Platform" asp-controller="Membership" asp-action="MembershipList">Aktif Paketler Listesini Görüntüle</a> |